### ISSUE TITLE
Issue when trying to use addtionals chart options

### ISSUE THREAD

**Issue by KrysD** [massmutual/dcr#2]
Hi, 
I'm trying to use dcr and i already know dc.js library.
But i dont understand how i can put additionals options to charts.
For example i would like to make the brush on an ordinal scale and not on a linear scale, like in the Days by Fluctuation(%) chart in the [example](https://huguyi10.shinyapps.io/stocks/). 
(Did you have the code of this example ?)

Can i put all the `.nameFunction ` of the dc library inside the dcrchart function ?
(for example `.gap(20)` is `gap=20` in dcr)

I have another question about the reset button, did i need to add it UI side manualy or can i put it server side when creating the chart ?

**Comment by XiangdongGu** [comment]
The code of the app can be found

https://github.com/massmutual/dcr/tree/master/inst/example/stocks

Add additional options are pretty simple and you can check the documentation at

https://github.com/massmutual/dcr/blob/master/dcr_documentation.Rmd

**Comment by KrysD** [comment]
Oh ! Ok wasn't thinking it will be so simple ! 
Thx for the links.

**Comment by KrysD** [comment]
I tried to make some barChart with the mtcars data set (for example with the drat variable).
The idea is to make an histogram, so i calculate the optimal size of the bins, it appear to be 0.5.
So i mutate the variable drat : 
```
mtcars = mutate(mtcars,
           drat = floor(drat/binsize)*binsize)
```
The i made a barChart like in dc.js with drat as dimension et and a reduceCount() to have the number of element in each bins. 
```
chart_drat <- dcrchart(type="barChart"
                           ,id="chart4"
                           ,dimension='drat'
                           , width = 400
                           , height = 250
                           ,reduce=reduceCount()
                           ,gap = 1
                           ,renderHorizontalGridLines = TRUE, elasticY = TRUE
                           ,yAxis = y_axis(ticks = 5)
                           ,xAxis = x_axis(ticks = 5))
```
But here is what i got 
![issue](https://cloud.githubusercontent.com/assets/13766508/19151794/035c31ae-8bcf-11e6-97e2-6a137f54a7bf.PNG)

I'm supposed to have a bin each 0.5 but the bins are overlaping.
Here is how it look like when i make a brush event.
![burshissue](https://cloud.githubusercontent.com/assets/13766508/19151852/61ba2eea-8bcf-11e6-88d0-03edb659b798.PNG)

**Comment by XiangdongGu** [comment]
I think it is the problem of calculating units by dc.js, see the link

http://stackoverflow.com/questions/15191258/properly-display-bin-width-in-barchart-using-dc-js-and-crossfilter-js

So you can use that solution by adding xUnits, the important part is to calculate how many xUnits, in your case you can try

`
rm(mtcars)
binsize = 0.1

mtcars = mutate(mtcars,
                drat = floor(drat/binsize)*binsize)

units_x <- diff(range(mtcars$drat) / binsize)

chart_drat <- dcrchart(type="barChart"
                      ,id="chart4"
                      ,dimension='drat'
                      , width = 400
                      , height = 250
                      ,reduce=reduceCount()
                      ,gap=1
                      ,xUnits = dc_code(sprintf("function() {return %s;}", units_x))
                      ,renderHorizontalGridLines = TRUE, elasticY = TRUE
                      ,yAxis = y_axis(ticks = 5)
                      ,xAxis = x_axis(ticks = 5))`

**Comment by KrysD** [comment]
Ok thx it works. 
I begin to understand how i can translate javascript inside the dcrchart function.
I hope not too upset with my questions.

Thank you again.

**Comment by XiangdongGu** [comment]
Actually what I usually get around this  is  to change the label in x axis while but x is still all integers

```
rm(mtcars)
binsize = 0.1
mtcars = mutate(mtcars,
                drat = floor(drat/binsize))

chart_drat <- dcrchart(type="barChart"
                       ,id="chart4"
                       ,dimension='drat'
                       , width = 400
                       , height = 250
                       , centerBar = TRUE
                       ,reduce=reduceCount()
                       ,gap=1
                       ,renderHorizontalGridLines = TRUE, elasticY = TRUE
                       ,yAxis = y_axis(ticks = 5)
                       ,xAxis = x_axis(ticks = 5,
                                       tickFormat = dc_code(sprintf("function(x) {return x * %s}", binsize))))
dcr(mtcars) + chart_drat
```

**Comment by KrysD** [comment]
Ok i undertand but if we need to go each 0.2 for exemple it didn't work.

What if i wanted to change the domain of the xAxis ?

**Comment by XiangdongGu** [comment]
Do you mean change the limit of the plot in x axis? There is a helper function called x_linear

for example 

rm(mtcars)
binsize = 0.2
mtcars = mutate(mtcars,
                drat = floor(drat/binsize))

```
chart_drat <- dcrchart(type="barChart"
                       ,id="chart4"
                       ,dimension='drat'
                       , width = 400
                       , height = 250
                       , centerBar = TRUE
                       ,reduce=reduceCount()
                       ,gap=1
                       , x=x_linear(c(12, 25))
                       ,renderHorizontalGridLines = TRUE, elasticY = TRUE
                       ,yAxis = y_axis(ticks = 5)
                       ,xAxis = x_axis(ticks = 5,
                                       tickFormat = dc_code(sprintf("function(x) {return (x * %s).toFixed(1);}", binsize))))
dcr(mtcars) + chart_drat
```

**Comment by KrysD** [comment]
Yes this is exactly what i mean !

**Comment by XiangdongGu** [comment]
You can try the following to add one bin of extra space in both sides

```
rm(mtcars)
binsize = 0.2

mtcars = mutate(mtcars,
                drat = floor(drat/binsize)*binsize)

xrange <- range(mtcars$drat)
nbin <- diff(xrange)/binsize + 1

units_x <- nbin + 2 #number of bin in the plot, and add extra bin both sides

chart_drat <- dcrchart(type="barChart"
                       ,id="chart4"
                       ,dimension='drat'
                       , width = 400
                       , height = 250
                       ,reduce=reduceCount()
                       ,gap=1
                       , x=x_linear(xrange + c(-binsize, binsize))
                       ,xUnits = dc_code(sprintf("function() {return %s;}", units_x))
                       ,renderHorizontalGridLines = TRUE, elasticY = TRUE
                       ,yAxis = y_axis(ticks = 5)
                       ,xAxis = x_axis(ticks = 5))

dcr(mtcars) + chart_drat
```

**Comment by KrysD** [comment]
Nice it's better ! 
Another thing i tried is to make the brush rounding. 
I added` round = dc_code(sprintf("dc.round.floor(function(n){return Math.floor(n/%s)*%s})",binsize,binsize))`
